// src/pages/GalleryPage.jsx
import { useCallback, useEffect, useMemo, useState } from 'react';
import { getLighttraceLibrary } from '../data/siteData';

const GALLERY_KEY = 'gallery_images_v1';
const MAX_IMAGES = 25;
const PAGE_SIZE = 25;

const localLibrary = getLighttraceLibrary();
const useLocalLibrary = localLibrary.length > 0;
const localLibraryHint = useLocalLibrary
    ? '当前为本地图库模式：请将图片放入 photos/lighttrace/ 并在 src/data/siteData.js 中配置。'
    : '';

function normalizeImage(item) {
    const src = item.src || item.file || item.data;
    return {
        id: item.id || src,
        data: src,
        title: item.title || item.fileName || item.id || src,
        comment: item.comment || '',
        createdAt: item.createdAt || item.date || '',
        date: item.date || item.createdAt || '',
        location: item.location || '',
        device: item.device || '',
        tags: item.tags || [],
        fileName: item.fileName || item.id || src
    };
}

function loadLocalLibrary() {
    return localLibrary.filter(item => item && (item.src || item.file)).map(normalizeImage);
}

function loadImages() {
    try {
        const stored = localStorage.getItem(GALLERY_KEY);
        const parsed = stored ? JSON.parse(stored) : [];
        return parsed.map(normalizeImage);
    } catch (e) {
        console.error('Failed to load images:', e);
        return [];
    }
}

function saveImages(images) {
    try {
        localStorage.setItem(GALLERY_KEY, JSON.stringify(images));
    } catch (e) {
        console.error('Failed to save images:', e);
        alert('保存失败：浏览器存储空间不足\n建议清除部分图片或清空浏览器缓存');
    }
}

export default function GalleryPage() {
    const [images, setImages] = useState(() => (useLocalLibrary ? loadLocalLibrary() : loadImages()));
    const [currentPage, setCurrentPage] = useState(1);
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [modalImage, setModalImage] = useState(null);

    const totalPages = useMemo(() => {
        if (!useLocalLibrary) return 1;
        return Math.max(1, Math.ceil(images.length / PAGE_SIZE));
    }, [images.length]);

    const pagedImages = useMemo(() => {
        if (!useLocalLibrary) return images;
        const page = Math.min(currentPage, totalPages);
        const start = (page - 1) * PAGE_SIZE;
        return images.slice(start, start + PAGE_SIZE);
    }, [currentPage, images, totalPages]);

    const modalImageIndex = useMemo(() => {
        if (!modalImage) return -1;
        return images.findIndex(img => img.id === modalImage.id);
    }, [images, modalImage]);

    const previousImage = modalImageIndex <= 0 ? null : images[modalImageIndex - 1];
    const nextImage = modalImageIndex < 0 || modalImageIndex >= images.length - 1 ? null : images[modalImageIndex + 1];
    const showEmpty = pagedImages.length === 0;
    const showPagination = useLocalLibrary && totalPages > 1;

    const updateHashForImage = useCallback(image => {
        if (!image || !image.id) return;
        history.replaceState(null, '', `#photo=${encodeURIComponent(image.id)}`);
    }, []);

    const openModal = useCallback((image, fromNav = false) => {
        if (!image) return;
        setModalImage(image);
        setIsModalOpen(true);
        document.body.style.overflow = 'hidden';
        if (!fromNav || image.id) updateHashForImage(image);
    }, [updateHashForImage]);

    const closeModal = useCallback(() => {
        setIsModalOpen(false);
        document.body.style.overflow = 'auto';
        setModalImage(null);
        if (location.hash.startsWith('#photo=')) {
            history.replaceState(null, '', location.pathname + location.search);
        }
    }, []);

    const openImageFromHash = useCallback(() => {
        const params = new URLSearchParams(location.hash.replace(/^#/, ''));
        const targetId = params.get('photo');
        if (!targetId) return;
        const targetIndex = images.findIndex(img => img.id === targetId || img.fileName === targetId);
        if (targetIndex < 0) return;
        setCurrentPage(Math.floor(targetIndex / PAGE_SIZE) + 1);
        openModal(images[targetIndex], true);
    }, [images, openModal]);

    useEffect(() => {
        openImageFromHash();
        window.addEventListener('hashchange', openImageFromHash);
        return () => {
            document.body.style.overflow = 'auto';
            window.removeEventListener('hashchange', openImageFromHash);
        };
    }, [openImageFromHash]);

    useEffect(() => {
        const handleKeydown = event => {
            if (!isModalOpen) return;
            if (event.key === 'Escape') closeModal();
            if (event.key === 'ArrowLeft' && previousImage) openModal(previousImage, true);
            if (event.key === 'ArrowRight' && nextImage) openModal(nextImage, true);
        };
        window.addEventListener('keydown', handleKeydown);
        return () => window.removeEventListener('keydown', handleKeydown);
    }, [closeModal, isModalOpen, nextImage, openModal, previousImage]);

    const displayCells = useMemo(() => {
        const cells = [];
        const cellCount = useLocalLibrary ? pagedImages.length : MAX_IMAGES;
        for (let i = 0; i < cellCount; i += 1) {
            if (i < pagedImages.length) {
                const img = pagedImages[i];
                cells.push({ key: img.id || i, type: 'image', ...img });
            } else {
                cells.push({ key: `placeholder-${i}`, type: 'placeholder' });
            }
        }
        return cells;
    }, [pagedImages]);

    function deleteImage() {
        if (!modalImage) return;
        if (!confirm('确定要删除这张图片吗？')) return;
        const nextImages = images.filter(img => img.id !== modalImage.id);
        setImages(nextImages);
        saveImages(nextImages);
        closeModal();
    }

    function editComment() {
        if (!modalImage) return;
        const newComment = prompt('编辑评注（最多100字）:', modalImage.comment || '');
        if (newComment === null) return;
        const trimmedComment = newComment.trim().slice(0, 100);
        const nextImages = images.map(img => img.id === modalImage.id ? { ...img, comment: trimmedComment } : img);
        setImages(nextImages);
        setModalImage({ ...modalImage, comment: trimmedComment });
        saveImages(nextImages);
    }

    function goToPage(page) {
        setCurrentPage(Math.max(1, Math.min(page, totalPages)));
    }

    return (
        <div>
            <header id="header" style={{ opacity: 1 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 12, width: '100%', maxWidth: 1100, justifyContent: 'space-between' }}>
                    <div style={{ fontWeight: 'bold', fontSize: 18 }}>
                        <a href="index.html" style={{ color: 'white', textDecoration: 'none' }}>Chen.のhomepage</a>
                    </div>
                    <div>
                        <a href="gallery.html" className="nav-btn" style={{ background: 'rgba(255, 255, 255, 0.2)' }}>光影留痕</a>
                        <a href="https://Bamb0oChen.github.io/notes/" className="nav-btn" target="_blank" rel="noopener noreferrer">笔记</a>
                    </div>
                </div>
            </header>

            <div className="gallery-container">
                <div className="gallery-header">
                    <h1>光影留痕</h1>
                    <p>记录生活中的精彩瞬间</p>
                </div>
                <div id="localLibraryHint" className="gallery-hint">{localLibraryHint}</div>

                <div className="gallery-grid">
                    {displayCells.map(cell => (
                        <button key={cell.key} className="gallery-cell" type="button" onClick={() => cell.type === 'image' && openModal(cell)}>
                            {cell.type === 'image' ? (
                                <>
                                    <img src={cell.data} alt={cell.title || cell.fileName} className="gallery-image" />
                                    {(cell.title || cell.comment) && (
                                        <div className="gallery-comment" title={cell.comment || cell.title}>
                                            {cell.title || cell.comment}
                                        </div>
                                    )}
                                </>
                            ) : (
                                <div className="gallery-placeholder">+</div>
                            )}
                        </button>
                    ))}
                </div>

                {showEmpty && <div className="gallery-empty"><p>暂无图片，点击 "上传图片" 开始</p></div>}

                {showPagination && (
                    <div className="gallery-pagination">
                        <button onClick={() => goToPage(currentPage - 1)} disabled={currentPage <= 1}>上一页</button>
                        <span>第 {currentPage} / {totalPages} 页</span>
                        <button onClick={() => goToPage(currentPage + 1)} disabled={currentPage >= totalPages}>下一页</button>
                    </div>
                )}
            </div>

            {isModalOpen && (
                <div className="modal" onClick={event => event.target === event.currentTarget && closeModal()}>
                    <div className="modal-content photo-detail-modal">
                        <button className="modal-close" type="button" aria-label="关闭" onClick={closeModal}>&times;</button>
                        <div className="modal-body">
                            <div className="detail-image-wrap">
                                <img src={modalImage?.data} alt={modalImage?.title || modalImage?.fileName || ''} />
                            </div>
                            <div className="modal-info">
                                <div>
                                    <div className="detail-kicker">Lighttrace</div>
                                    <h2 className="detail-title">{modalImage?.title || modalImage?.fileName || '未命名光影'}</h2>
                                    <div className="detail-meta">
                                        {modalImage?.date && <span>{modalImage.date}</span>}
                                        {modalImage?.location && <span>{modalImage.location}</span>}
                                        {modalImage?.device && <span>{modalImage.device}</span>}
                                    </div>
                                    {!!modalImage?.tags?.length && (
                                        <div className="detail-tags">
                                            {modalImage.tags.map(tag => <span key={tag}>{tag}</span>)}
                                        </div>
                                    )}
                                    {modalImage?.comment ? <div className="modal-comment">{modalImage.comment}</div> : <div className="modal-comment muted">暂无评注</div>}
                                </div>
                                <div className="modal-actions">
                                    <div className="detail-nav">
                                        <button className="modal-btn" type="button" disabled={!previousImage} onClick={() => openModal(previousImage, true)}>上一张</button>
                                        <button className="modal-btn" type="button" disabled={!nextImage} onClick={() => openModal(nextImage, true)}>下一张</button>
                                    </div>
                                    {!useLocalLibrary && <button className="modal-btn delete-btn" type="button" onClick={deleteImage}>删除</button>}
                                    {!useLocalLibrary && <button className="modal-btn edit-btn" type="button" onClick={editComment}>编辑评注</button>}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}

// src/pages/GalleryPage.vue
<template>
    <div>
        <header id="header" style="opacity: 1;">
            <div style="display:flex; align-items:center; gap:12px; width:100%; max-width:1100px; justify-content:space-between;">
                <div style="font-weight:bold; font-size:18px;">
                    <a href="index.html" style="color: white; text-decoration: none;">Chen.のhomepage</a>
                </div>
                <div>
                    <a href="gallery.html" class="nav-btn" style="background: rgba(255, 255, 255, 0.2);">光影留痕</a>
                    <a href="https://Bamb0oChen.github.io/notes/" class="nav-btn" target="_blank" rel="noopener noreferrer">笔记</a>
                </div>
            </div>
        </header>

        <div class="gallery-container">
            <div class="gallery-header">
                <h1>光影留痕</h1>
                <p>记录生活中的精彩瞬间</p>
            </div>
            <div id="localLibraryHint" class="gallery-hint">{{ localLibraryHint }}</div>

            <div class="gallery-grid">
                <button v-for="cell in displayCells" :key="cell.key" class="gallery-cell" type="button" @click="cell.onClick">
                    <template v-if="cell.type === 'image'">
                        <img :src="cell.data" :alt="cell.title || cell.fileName" class="gallery-image" />
                        <div v-if="cell.title || cell.comment" class="gallery-comment" :title="cell.comment || cell.title">
                            {{ cell.title || cell.comment }}
                        </div>
                    </template>
                    <template v-else>
                        <div class="gallery-placeholder">+</div>
                    </template>
                </button>
            </div>

            <div v-if="showEmpty" class="gallery-empty">
                <p>暂无图片，点击 "上传图片" 开始</p>
            </div>

            <div class="gallery-pagination" v-if="showPagination">
                <button @click="goToPage(currentPage - 1)" :disabled="currentPage <= 1">上一页</button>
                <span>第 {{ currentPage }} / {{ totalPages }} 页</span>
                <button @click="goToPage(currentPage + 1)" :disabled="currentPage >= totalPages">下一页</button>
            </div>
        </div>

        <div class="modal" v-show="isModalOpen" @click.self="closeModal">
            <div class="modal-content photo-detail-modal">
                <button class="modal-close" type="button" aria-label="关闭" @click="closeModal">&times;</button>
                <div class="modal-body">
                    <div class="detail-image-wrap">
                        <img :src="modalImage?.data" :alt="modalImage?.title || modalImage?.fileName || ''" />
                    </div>
                    <div class="modal-info">
                        <div>
                            <div class="detail-kicker">Lighttrace</div>
                            <h2 class="detail-title">{{ modalImage?.title || modalImage?.fileName || '未命名光影' }}</h2>
                            <div class="detail-meta">
                                <span v-if="modalImage?.date">{{ modalImage.date }}</span>
                                <span v-if="modalImage?.location">{{ modalImage.location }}</span>
                                <span v-if="modalImage?.device">{{ modalImage.device }}</span>
                            </div>
                            <div v-if="modalImage?.tags?.length" class="detail-tags">
                                <span v-for="tag in modalImage.tags" :key="tag">{{ tag }}</span>
                            </div>
                            <div v-if="modalImage?.comment" class="modal-comment">{{ modalImage.comment }}</div>
                            <div v-else class="modal-comment muted">暂无评注</div>
                        </div>
                        <div class="modal-actions">
                            <div class="detail-nav">
                                <button class="modal-btn" type="button" :disabled="!previousImage" @click="openModal(previousImage, true)">上一张</button>
                                <button class="modal-btn" type="button" :disabled="!nextImage" @click="openModal(nextImage, true)">下一张</button>
                            </div>
                            <button v-if="!useLocalLibrary" class="modal-btn delete-btn" type="button" @click="deleteImage">删除</button>
                            <button v-if="!useLocalLibrary" class="modal-btn edit-btn" type="button" @click="editComment">编辑评注</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import { getLighttraceLibrary } from '../data/siteData';

const GALLERY_KEY = 'gallery_images_v1';
const MAX_IMAGES = 25;
const PAGE_SIZE = 25;

const localLibrary = getLighttraceLibrary();
const useLocalLibrary = localLibrary.length > 0;
const localLibraryHint = useLocalLibrary ? '当前为本地图库模式：请将图片放入 photos/lighttrace/ 并在 src/data/siteData.js 中配置。' : '';

const images = ref(useLocalLibrary ? loadLocalLibrary() : loadImages());
const currentPage = ref(1);
const isModalOpen = ref(false);
const modalImage = ref(null);

const modalImageIndex = computed(() => {
    if (!modalImage.value) return -1;
    return images.value.findIndex(img => img.id === modalImage.value.id);
});

const previousImage = computed(() => {
    const index = modalImageIndex.value;
    if (index <= 0) return null;
    return images.value[index - 1];
});

const nextImage = computed(() => {
    const index = modalImageIndex.value;
    if (index < 0 || index >= images.value.length - 1) return null;
    return images.value[index + 1];
});

function normalizeImage(item) {
    const src = item.src || item.file || item.data;
    return {
        id: item.id || src,
        data: src,
        title: item.title || item.fileName || item.id || src,
        comment: item.comment || '',
        createdAt: item.createdAt || item.date || '',
        date: item.date || item.createdAt || '',
        location: item.location || '',
        device: item.device || '',
        tags: item.tags || [],
        fileName: item.fileName || item.id || src
    };
}

function loadLocalLibrary() {
    return localLibrary.filter(item => item && (item.src || item.file)).map(normalizeImage);
}

function loadImages() {
    try {
        const stored = localStorage.getItem(GALLERY_KEY);
        const parsed = stored ? JSON.parse(stored) : [];
        return parsed.map(normalizeImage);
    } catch (e) {
        console.error('Failed to load images:', e);
        return [];
    }
}

function saveImages() {
    try {
        localStorage.setItem(GALLERY_KEY, JSON.stringify(images.value));
    } catch (e) {
        console.error('Failed to save images:', e);
        alert('保存失败：浏览器存储空间不足\n建议清除部分图片或清空浏览器缓存');
    }
}

const totalPages = computed(() => {
    if (!useLocalLibrary) return 1;
    return Math.max(1, Math.ceil(images.value.length / PAGE_SIZE));
});

const pagedImages = computed(() => {
    if (!useLocalLibrary) return images.value;
    const page = Math.min(currentPage.value, totalPages.value);
    const start = (page - 1) * PAGE_SIZE;
    return images.value.slice(start, start + PAGE_SIZE);
});

const displayCells = computed(() => {
    const cells = [];
    const list = pagedImages.value;
    const cellCount = useLocalLibrary ? list.length : MAX_IMAGES;

    for (let i = 0; i < cellCount; i++) {
        if (i < list.length) {
            const img = list[i];
            cells.push({
                key: img.id || i,
                type: 'image',
                ...img,
                onClick: () => openModal(img)
            });
        } else {
            cells.push({
                key: `placeholder-${i}`,
                type: 'placeholder',
                onClick: () => {}
            });
        }
    }

    return cells;
});

const showEmpty = computed(() => pagedImages.value.length === 0);
const showPagination = computed(() => useLocalLibrary && totalPages.value > 1);

function updateHashForImage(image) {
    if (!image || !image.id) return;
    history.replaceState(null, '', `#photo=${encodeURIComponent(image.id)}`);
}

function openModal(image, fromNav = false) {
    if (!image) return;
    modalImage.value = image;
    isModalOpen.value = true;
    document.body.style.overflow = 'hidden';
    if (!fromNav || image.id) updateHashForImage(image);
}

function closeModal() {
    isModalOpen.value = false;
    document.body.style.overflow = 'auto';
    modalImage.value = null;
    if (location.hash.startsWith('#photo=')) {
        history.replaceState(null, '', location.pathname + location.search);
    }
}

function deleteImage() {
    if (!modalImage.value) return;
    if (!confirm('确定要删除这张图片吗？')) return;

    images.value = images.value.filter(img => img.id !== modalImage.value.id);
    saveImages();
    closeModal();
}

function editComment() {
    if (!modalImage.value) return;
    const newComment = prompt('编辑评注（最多 100字）:', modalImage.value.comment || '');
    if (newComment === null) return;

    const trimmedComment = newComment.trim().slice(0, 100);
    modalImage.value.comment = trimmedComment;
    saveImages();
}

function goToPage(page) {
    const next = Math.max(1, Math.min(page, totalPages.value));
    currentPage.value = next;
}

function openImageFromHash() {
    const params = new URLSearchParams(location.hash.replace(/^#/, ''));
    const targetId = params.get('photo');
    if (!targetId) return;
    const targetIndex = images.value.findIndex(img => img.id === targetId || img.fileName === targetId);
    if (targetIndex < 0) return;
    currentPage.value = Math.floor(targetIndex / PAGE_SIZE) + 1;
    openModal(images.value[targetIndex], true);
}

function handleKeydown(event) {
    if (!isModalOpen.value) return;
    if (event.key === 'Escape') closeModal();
    if (event.key === 'ArrowLeft' && previousImage.value) openModal(previousImage.value, true);
    if (event.key === 'ArrowRight' && nextImage.value) openModal(nextImage.value, true);
}

onMounted(() => {
    openImageFromHash();
    window.addEventListener('hashchange', openImageFromHash);
    window.addEventListener('keydown', handleKeydown);
});

onBeforeUnmount(() => {
    document.body.style.overflow = 'auto';
    window.removeEventListener('hashchange', openImageFromHash);
    window.removeEventListener('keydown', handleKeydown);
});
</script>
